#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/niri"
RASI="$DIR/rofi/bindings.rasi"

# Run
cat $DIR/lo_key_bindings.txt | rofi \
     -dmenu \
     -theme ${RASI}
