#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Niri

WALLPAPER='/home/username/Pictures/wallpapers/ign_dudeOnBuilding2.png'

swaybg --output '*' --mode fill --image "$WALLPAPER" "-c" "#000000"
